# 불 자료형은 어떻게 사용할까?
# a = True
# b = False
# c = 'True'

# print(a)
# print(c)

# print(type(c))

# type(b)

# print(1 == 1)
# print(2 > 1)
# print(2 < 1)
# a = 59
# b = 1

# 자료형의 참과 거짓
# if a > 70:
#     print("합격")
# elif a > 60:
#     print("보류")
# else:
#     print("불합격")

# if [1, 2, 3]:
#     print("참")
# else:
#     print("거짓")
# 

# 불 연산
# bool('python')

# bool([1, 2, 3])

# bool([])

# bool(0)

# bool(3)